[initial message not restored]

----------------------------------------------------------------------------
Author:     favoritas37
Created:    02/25/11 15:52:34

----------------------------------------------------------------------------

I thing in Visual Studio, above this lie=ne that you mentioned: "Expression: _BLOCK_TYPE_IS_VALID(phead->nBlockUse) "
there is line stating the file and the line number where it took place. Would it be easy for you to post this as well?....or the entire console output....

----------------------------------------------------------------------------
Author:     user1
Created:    02/25/11 16:09:58

----------------------------------------------------------------------------

The console output is:

Debug Assertion Failed!

Program:

C:\!QtProjects\..\QBtMng.exe

File: f:\dd\vctools\crt_bld\self_x86\crt\src\dbgdel.cpp

Line: 52

Expression: _BLOCK_TYPE_IS_VALID(phead->nBlockUse)

----------------------------------------------------------------------------
Author:     favoritas37
Created:    02/25/11 17:54:08

----------------------------------------------------------------------------

I am afraid i can't reproduce it....

It would be really convenient if you could mail me your whole Visual Studio solution to take a look at...(mail: ftylitak@gmail.com)

I say that because the windows part of the library has some drawbacks because of the library that is used. It has some static functions for callbacks and maybe in some cases those static functions access invalid objects.

----------------------------------------------------------------------------
Author:     favoritas37
Created:    02/25/11 18:32:27

----------------------------------------------------------------------------

Can you please try the following version of the library and let me know?

https://projects.forum.nokia.com/qbluetooth/files/QBluetooth.zip

----------------------------------------------------------------------------
Author:     user1
Created:    02/27/11 17:35:49

----------------------------------------------------------------------------

Many Thanks favoritas37!

I downloaded the version http://wiki.forum.nokia.com/index.php/QBluetooth_-_A_Qt_bluetooth_library of library and I replaced old files file contained in it with new files in https://projects.forum.nokia.com/qbluetooth/changeset/37

Now my application works!!!! :)